2023-11-15 22:51:12,827:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:12,827:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:12,827:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:12,827:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:42,345:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:42,345:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:42,345:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:42,345:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-15 22:51:42,759:INFO:PyCaret ClassificationExperiment
2023-11-15 22:51:42,759:INFO:Logging name: clf-default-name
2023-11-15 22:51:42,759:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-15 22:51:42,759:INFO:version 3.1.0
2023-11-15 22:51:42,759:INFO:Initializing setup()
2023-11-15 22:51:42,759:INFO:self.USI: 1795
2023-11-15 22:51:42,759:INFO:self._variable_keys: {'_ml_usecase', 'X_test', 'seed', 'idx', 'X', 'pipeline', 'X_train', 'y_test', 'n_jobs_param', 'y_train', 'is_multiclass', 'memory', 'y', 'exp_name_log', 'fix_imbalance', 'fold_generator', 'fold_shuffle_param', 'log_plots_param', 'html_param', 'gpu_param', 'target_param', 'fold_groups_param', 'logging_param', 'USI', '_available_plots', 'gpu_n_jobs_param', 'exp_id', 'data'}
2023-11-15 22:51:42,759:INFO:Checking environment
2023-11-15 22:51:42,759:INFO:python_version: 3.9.18
2023-11-15 22:51:42,759:INFO:python_build: ('main', 'Sep 11 2023 13:41:44')
2023-11-15 22:51:42,759:INFO:machine: x86_64
2023-11-15 22:51:42,759:INFO:platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
2023-11-15 22:51:42,760:INFO:Memory: svmem(total=67359436800, available=64132997120, percent=4.8, used=2536873984, free=62625615872, active=527265792, inactive=3495727104, buffers=142086144, cached=2054860800, shared=24522752, slab=257548288)
2023-11-15 22:51:42,760:INFO:Physical Core: 6
2023-11-15 22:51:42,760:INFO:Logical Core: 12
2023-11-15 22:51:42,760:INFO:Checking libraries
2023-11-15 22:51:42,760:INFO:System:
2023-11-15 22:51:42,760:INFO:    python: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
2023-11-15 22:51:42,760:INFO:executable: /home/mlam/anaconda3/envs/py39/bin/python
2023-11-15 22:51:42,760:INFO:   machine: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
2023-11-15 22:51:42,760:INFO:PyCaret required dependencies:
2023-11-15 22:51:42,795:INFO:                 pip: 23.3
2023-11-15 22:51:42,795:INFO:          setuptools: 68.0.0
2023-11-15 22:51:42,795:INFO:             pycaret: 3.1.0
2023-11-15 22:51:42,795:INFO:             IPython: 8.16.1
2023-11-15 22:51:42,795:INFO:          ipywidgets: 8.1.1
2023-11-15 22:51:42,795:INFO:                tqdm: 4.66.1
2023-11-15 22:51:42,795:INFO:               numpy: 1.23.5
2023-11-15 22:51:42,795:INFO:              pandas: 1.5.3
2023-11-15 22:51:42,795:INFO:              jinja2: 3.1.2
2023-11-15 22:51:42,795:INFO:               scipy: 1.10.1
2023-11-15 22:51:42,795:INFO:              joblib: 1.3.2
2023-11-15 22:51:42,795:INFO:             sklearn: 1.2.2
2023-11-15 22:51:42,795:INFO:                pyod: 1.1.1
2023-11-15 22:51:42,795:INFO:            imblearn: 0.11.0
2023-11-15 22:51:42,795:INFO:   category_encoders: 2.6.2
2023-11-15 22:51:42,795:INFO:            lightgbm: 4.1.0
2023-11-15 22:51:42,795:INFO:               numba: 0.58.1
2023-11-15 22:51:42,795:INFO:            requests: 2.31.0
2023-11-15 22:51:42,795:INFO:          matplotlib: 3.8.0
2023-11-15 22:51:42,795:INFO:          scikitplot: 0.3.7
2023-11-15 22:51:42,795:INFO:         yellowbrick: 1.5
2023-11-15 22:51:42,795:INFO:              plotly: 5.18.0
2023-11-15 22:51:42,795:INFO:    plotly-resampler: Not installed
2023-11-15 22:51:42,795:INFO:             kaleido: 0.2.1
2023-11-15 22:51:42,795:INFO:           schemdraw: 0.15
2023-11-15 22:51:42,795:INFO:         statsmodels: 0.14.0
2023-11-15 22:51:42,795:INFO:              sktime: 0.21.1
2023-11-15 22:51:42,795:INFO:               tbats: 1.1.3
2023-11-15 22:51:42,795:INFO:            pmdarima: 2.0.4
2023-11-15 22:51:42,795:INFO:              psutil: 5.9.6
2023-11-15 22:51:42,795:INFO:          markupsafe: 2.1.2
2023-11-15 22:51:42,795:INFO:             pickle5: Not installed
2023-11-15 22:51:42,795:INFO:         cloudpickle: 2.2.1
2023-11-15 22:51:42,795:INFO:         deprecation: 2.1.0
2023-11-15 22:51:42,795:INFO:              xxhash: 3.4.1
2023-11-15 22:51:42,795:INFO:           wurlitzer: 3.0.3
2023-11-15 22:51:42,795:INFO:PyCaret optional dependencies:
2023-11-15 22:51:42,804:INFO:                shap: Not installed
2023-11-15 22:51:42,805:INFO:           interpret: Not installed
2023-11-15 22:51:42,805:INFO:                umap: Not installed
2023-11-15 22:51:42,805:INFO:     ydata_profiling: Not installed
2023-11-15 22:51:42,805:INFO:  explainerdashboard: Not installed
2023-11-15 22:51:42,805:INFO:             autoviz: Not installed
2023-11-15 22:51:42,805:INFO:           fairlearn: Not installed
2023-11-15 22:51:42,805:INFO:          deepchecks: Not installed
2023-11-15 22:51:42,805:INFO:             xgboost: 2.0.1
2023-11-15 22:51:42,805:INFO:            catboost: 1.2.2
2023-11-15 22:51:42,805:INFO:              kmodes: Not installed
2023-11-15 22:51:42,805:INFO:             mlxtend: Not installed
2023-11-15 22:51:42,805:INFO:       statsforecast: Not installed
2023-11-15 22:51:42,805:INFO:        tune_sklearn: Not installed
2023-11-15 22:51:42,805:INFO:                 ray: Not installed
2023-11-15 22:51:42,805:INFO:            hyperopt: Not installed
2023-11-15 22:51:42,805:INFO:              optuna: Not installed
2023-11-15 22:51:42,805:INFO:               skopt: Not installed
2023-11-15 22:51:42,805:INFO:              mlflow: 2.8.0
2023-11-15 22:51:42,805:INFO:              gradio: Not installed
2023-11-15 22:51:42,805:INFO:             fastapi: Not installed
2023-11-15 22:51:42,805:INFO:             uvicorn: Not installed
2023-11-15 22:51:42,805:INFO:              m2cgen: Not installed
2023-11-15 22:51:42,805:INFO:           evidently: Not installed
2023-11-15 22:51:42,805:INFO:               fugue: Not installed
2023-11-15 22:51:42,805:INFO:           streamlit: 1.28.1
2023-11-15 22:51:42,805:INFO:             prophet: Not installed
2023-11-15 22:51:42,805:INFO:None
2023-11-15 22:51:42,805:INFO:Set up data.
2023-11-15 22:51:42,813:INFO:Set up folding strategy.
2023-11-15 22:51:42,813:INFO:Set up train/test split.
2023-11-15 22:51:42,817:INFO:Set up index.
2023-11-15 22:51:42,817:INFO:Assigning column types.
2023-11-15 22:51:42,819:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-15 22:51:42,855:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-15 22:51:42,857:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-15 22:51:42,882:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:42,884:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:42,921:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-15 22:51:42,922:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-15 22:51:42,943:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:42,945:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:42,946:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-15 22:51:42,982:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-15 22:51:43,004:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,006:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,043:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-15 22:51:43,064:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,066:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,067:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-15 22:51:43,124:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,126:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,184:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,186:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,188:INFO:Preparing preprocessing pipeline...
2023-11-15 22:51:43,190:INFO:Set up label encoding.
2023-11-15 22:51:43,190:INFO:Set up simple imputation.
2023-11-15 22:51:43,190:INFO:Set up polynomial features.
2023-11-15 22:51:43,190:INFO:Set up imbalanced handling.
2023-11-15 22:51:43,190:INFO:Set up feature normalization.
2023-11-15 22:51:43,285:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:43,383:INFO:Finished creating preprocessing pipeline.
2023-11-15 22:51:43,391:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Length', 'Diameter', 'Height',
                                             'Whole_weight', 'Shucked_weight',
                                             'Viscera_weight', 'Shell_weight',
                                             'Rings'],
                                    transformer=SimpleImputer(a...
                                                                   include_bias=False,
                                                                   interaction_only=False,
                                                                   order='C'))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              n_jobs=None,
                                                                              random_state=29,
                                                                              sampling_strategy='auto')))),
                ('normalize',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=StandardScaler(copy=True,
                                                               with_mean=True,
                                                               with_std=True)))],
         verbose=False)
2023-11-15 22:51:43,391:INFO:Creating final display dataframe.
2023-11-15 22:51:43,533:INFO:Setup _display_container:                     Description             Value
0                    Session id                29
1                        Target               Sex
2                   Target type        Multiclass
3                Target mapping  F: 0, I: 1, M: 2
4           Original data shape         (3341, 9)
5        Transformed data shape        (3599, 45)
6   Transformed train set shape        (2763, 45)
7    Transformed test set shape         (836, 45)
8              Numeric features                 8
9                    Preprocess              True
10              Imputation type            simple
11           Numeric imputation              mean
12       Categorical imputation              mode
13          Polynomial features              True
14            Polynomial degree                 2
15                Fix imbalance              True
16         Fix imbalance method             smote
17                    Normalize              True
18             Normalize method            zscore
19               Fold Generator   StratifiedKFold
20                  Fold Number                10
21                     CPU Jobs                -1
22                      Use GPU             False
23               Log Experiment             False
24              Experiment Name  clf-default-name
25                          USI              1795
2023-11-15 22:51:43,613:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,616:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,686:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,688:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,689:INFO:setup() successfully completed in 0.93s...............
2023-11-15 22:51:43,689:INFO:gpu_param set to False
2023-11-15 22:51:43,748:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,751:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,810:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-15 22:51:43,812:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-15 22:51:43,820:INFO:Initializing compare_models()
2023-11-15 22:51:43,820:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, include=None, fold=None, round=4, cross_validation=True, sort=AUC, n_select=3, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'AUC', 'n_select': 3, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-15 22:51:43,820:INFO:Checking exceptions
2023-11-15 22:51:43,823:INFO:Preparing display monitor
2023-11-15 22:51:43,839:INFO:Initializing Logistic Regression
2023-11-15 22:51:43,839:INFO:Total runtime is 2.11795171101888e-06 minutes
2023-11-15 22:51:43,841:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:43,841:INFO:Initializing create_model()
2023-11-15 22:51:43,841:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:43,841:INFO:Checking exceptions
2023-11-15 22:51:43,841:INFO:Importing libraries
2023-11-15 22:51:43,841:INFO:Copying training dataset
2023-11-15 22:51:43,844:INFO:Defining folds
2023-11-15 22:51:43,844:INFO:Declaring metric variables
2023-11-15 22:51:43,846:INFO:Importing untrained model
2023-11-15 22:51:43,849:INFO:Logistic Regression Imported successfully
2023-11-15 22:51:43,854:INFO:Starting cross validation
2023-11-15 22:51:43,855:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:45,305:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,306:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,345:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,350:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,404:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,467:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,500:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,542:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,551:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,588:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:45,906:INFO:Calculating mean and std
2023-11-15 22:51:45,907:INFO:Creating metrics dataframe
2023-11-15 22:51:45,912:INFO:Uploading results into container
2023-11-15 22:51:45,912:INFO:Uploading model into container now
2023-11-15 22:51:45,913:INFO:_master_model_container: 1
2023-11-15 22:51:45,913:INFO:_display_container: 2
2023-11-15 22:51:45,913:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=29, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-15 22:51:45,913:INFO:create_model() successfully completed......................................
2023-11-15 22:51:46,007:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:46,008:INFO:Creating metrics dataframe
2023-11-15 22:51:46,016:INFO:Initializing K Neighbors Classifier
2023-11-15 22:51:46,016:INFO:Total runtime is 0.03627590735753377 minutes
2023-11-15 22:51:46,018:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:46,018:INFO:Initializing create_model()
2023-11-15 22:51:46,018:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:46,018:INFO:Checking exceptions
2023-11-15 22:51:46,018:INFO:Importing libraries
2023-11-15 22:51:46,018:INFO:Copying training dataset
2023-11-15 22:51:46,022:INFO:Defining folds
2023-11-15 22:51:46,022:INFO:Declaring metric variables
2023-11-15 22:51:46,025:INFO:Importing untrained model
2023-11-15 22:51:46,028:INFO:K Neighbors Classifier Imported successfully
2023-11-15 22:51:46,033:INFO:Starting cross validation
2023-11-15 22:51:46,034:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:46,920:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:46,925:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/threadpoolctl.py:1010: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

2023-11-15 22:51:46,994:INFO:Calculating mean and std
2023-11-15 22:51:46,995:INFO:Creating metrics dataframe
2023-11-15 22:51:46,999:INFO:Uploading results into container
2023-11-15 22:51:46,999:INFO:Uploading model into container now
2023-11-15 22:51:47,000:INFO:_master_model_container: 2
2023-11-15 22:51:47,000:INFO:_display_container: 2
2023-11-15 22:51:47,000:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-15 22:51:47,000:INFO:create_model() successfully completed......................................
2023-11-15 22:51:47,099:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:47,099:INFO:Creating metrics dataframe
2023-11-15 22:51:47,106:INFO:Initializing Naive Bayes
2023-11-15 22:51:47,106:INFO:Total runtime is 0.05444383223851522 minutes
2023-11-15 22:51:47,108:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:47,108:INFO:Initializing create_model()
2023-11-15 22:51:47,108:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:47,108:INFO:Checking exceptions
2023-11-15 22:51:47,108:INFO:Importing libraries
2023-11-15 22:51:47,108:INFO:Copying training dataset
2023-11-15 22:51:47,111:INFO:Defining folds
2023-11-15 22:51:47,111:INFO:Declaring metric variables
2023-11-15 22:51:47,113:INFO:Importing untrained model
2023-11-15 22:51:47,115:INFO:Naive Bayes Imported successfully
2023-11-15 22:51:47,118:INFO:Starting cross validation
2023-11-15 22:51:47,119:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:47,209:INFO:Calculating mean and std
2023-11-15 22:51:47,210:INFO:Creating metrics dataframe
2023-11-15 22:51:47,212:INFO:Uploading results into container
2023-11-15 22:51:47,213:INFO:Uploading model into container now
2023-11-15 22:51:47,213:INFO:_master_model_container: 3
2023-11-15 22:51:47,213:INFO:_display_container: 2
2023-11-15 22:51:47,213:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-15 22:51:47,213:INFO:create_model() successfully completed......................................
2023-11-15 22:51:47,290:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:47,290:INFO:Creating metrics dataframe
2023-11-15 22:51:47,297:INFO:Initializing Decision Tree Classifier
2023-11-15 22:51:47,297:INFO:Total runtime is 0.05763003428777059 minutes
2023-11-15 22:51:47,299:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:47,299:INFO:Initializing create_model()
2023-11-15 22:51:47,299:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:47,299:INFO:Checking exceptions
2023-11-15 22:51:47,299:INFO:Importing libraries
2023-11-15 22:51:47,299:INFO:Copying training dataset
2023-11-15 22:51:47,302:INFO:Defining folds
2023-11-15 22:51:47,303:INFO:Declaring metric variables
2023-11-15 22:51:47,305:INFO:Importing untrained model
2023-11-15 22:51:47,308:INFO:Decision Tree Classifier Imported successfully
2023-11-15 22:51:47,313:INFO:Starting cross validation
2023-11-15 22:51:47,314:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:47,496:INFO:Calculating mean and std
2023-11-15 22:51:47,496:INFO:Creating metrics dataframe
2023-11-15 22:51:47,499:INFO:Uploading results into container
2023-11-15 22:51:47,499:INFO:Uploading model into container now
2023-11-15 22:51:47,499:INFO:_master_model_container: 4
2023-11-15 22:51:47,499:INFO:_display_container: 2
2023-11-15 22:51:47,499:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=29, splitter='best')
2023-11-15 22:51:47,499:INFO:create_model() successfully completed......................................
2023-11-15 22:51:47,579:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:47,579:INFO:Creating metrics dataframe
2023-11-15 22:51:47,585:INFO:Initializing SVM - Linear Kernel
2023-11-15 22:51:47,585:INFO:Total runtime is 0.06243570645650228 minutes
2023-11-15 22:51:47,587:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:47,587:INFO:Initializing create_model()
2023-11-15 22:51:47,587:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:47,587:INFO:Checking exceptions
2023-11-15 22:51:47,588:INFO:Importing libraries
2023-11-15 22:51:47,588:INFO:Copying training dataset
2023-11-15 22:51:47,590:INFO:Defining folds
2023-11-15 22:51:47,590:INFO:Declaring metric variables
2023-11-15 22:51:47,592:INFO:Importing untrained model
2023-11-15 22:51:47,594:INFO:SVM - Linear Kernel Imported successfully
2023-11-15 22:51:47,597:INFO:Starting cross validation
2023-11-15 22:51:47,598:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:47,713:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,720:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,720:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,722:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,740:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,740:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,740:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,746:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,756:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,775:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-15 22:51:47,785:INFO:Calculating mean and std
2023-11-15 22:51:47,786:INFO:Creating metrics dataframe
2023-11-15 22:51:47,789:INFO:Uploading results into container
2023-11-15 22:51:47,789:INFO:Uploading model into container now
2023-11-15 22:51:47,789:INFO:_master_model_container: 5
2023-11-15 22:51:47,789:INFO:_display_container: 2
2023-11-15 22:51:47,790:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=29, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-15 22:51:47,790:INFO:create_model() successfully completed......................................
2023-11-15 22:51:47,868:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:47,868:INFO:Creating metrics dataframe
2023-11-15 22:51:47,875:INFO:Initializing Ridge Classifier
2023-11-15 22:51:47,875:INFO:Total runtime is 0.0672696590423584 minutes
2023-11-15 22:51:47,877:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:47,877:INFO:Initializing create_model()
2023-11-15 22:51:47,878:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:47,878:INFO:Checking exceptions
2023-11-15 22:51:47,878:INFO:Importing libraries
2023-11-15 22:51:47,878:INFO:Copying training dataset
2023-11-15 22:51:47,880:INFO:Defining folds
2023-11-15 22:51:47,880:INFO:Declaring metric variables
2023-11-15 22:51:47,882:INFO:Importing untrained model
2023-11-15 22:51:47,884:INFO:Ridge Classifier Imported successfully
2023-11-15 22:51:47,888:INFO:Starting cross validation
2023-11-15 22:51:47,889:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:47,961:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,961:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,962:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,962:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,965:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,966:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,968:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,968:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,976:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,979:WARNING:/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/mlam/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-15 22:51:47,990:INFO:Calculating mean and std
2023-11-15 22:51:47,990:INFO:Creating metrics dataframe
2023-11-15 22:51:47,993:INFO:Uploading results into container
2023-11-15 22:51:47,993:INFO:Uploading model into container now
2023-11-15 22:51:47,993:INFO:_master_model_container: 6
2023-11-15 22:51:47,993:INFO:_display_container: 2
2023-11-15 22:51:47,994:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=29, solver='auto',
                tol=0.0001)
2023-11-15 22:51:47,994:INFO:create_model() successfully completed......................................
2023-11-15 22:51:48,069:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:48,069:INFO:Creating metrics dataframe
2023-11-15 22:51:48,076:INFO:Initializing Random Forest Classifier
2023-11-15 22:51:48,076:INFO:Total runtime is 0.07061692078908285 minutes
2023-11-15 22:51:48,078:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:48,078:INFO:Initializing create_model()
2023-11-15 22:51:48,078:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:48,079:INFO:Checking exceptions
2023-11-15 22:51:48,079:INFO:Importing libraries
2023-11-15 22:51:48,079:INFO:Copying training dataset
2023-11-15 22:51:48,081:INFO:Defining folds
2023-11-15 22:51:48,081:INFO:Declaring metric variables
2023-11-15 22:51:48,083:INFO:Importing untrained model
2023-11-15 22:51:48,085:INFO:Random Forest Classifier Imported successfully
2023-11-15 22:51:48,089:INFO:Starting cross validation
2023-11-15 22:51:48,090:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:49,121:INFO:Calculating mean and std
2023-11-15 22:51:49,122:INFO:Creating metrics dataframe
2023-11-15 22:51:49,125:INFO:Uploading results into container
2023-11-15 22:51:49,125:INFO:Uploading model into container now
2023-11-15 22:51:49,126:INFO:_master_model_container: 7
2023-11-15 22:51:49,126:INFO:_display_container: 2
2023-11-15 22:51:49,126:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=29, verbose=0, warm_start=False)
2023-11-15 22:51:49,126:INFO:create_model() successfully completed......................................
2023-11-15 22:51:49,206:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:49,206:INFO:Creating metrics dataframe
2023-11-15 22:51:49,214:INFO:Initializing Quadratic Discriminant Analysis
2023-11-15 22:51:49,214:INFO:Total runtime is 0.0895764152208964 minutes
2023-11-15 22:51:49,216:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:49,216:INFO:Initializing create_model()
2023-11-15 22:51:49,216:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:49,216:INFO:Checking exceptions
2023-11-15 22:51:49,216:INFO:Importing libraries
2023-11-15 22:51:49,216:INFO:Copying training dataset
2023-11-15 22:51:49,219:INFO:Defining folds
2023-11-15 22:51:49,219:INFO:Declaring metric variables
2023-11-15 22:51:49,221:INFO:Importing untrained model
2023-11-15 22:51:49,223:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-15 22:51:49,228:INFO:Starting cross validation
2023-11-15 22:51:49,229:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:49,333:INFO:Calculating mean and std
2023-11-15 22:51:49,334:INFO:Creating metrics dataframe
2023-11-15 22:51:49,336:INFO:Uploading results into container
2023-11-15 22:51:49,337:INFO:Uploading model into container now
2023-11-15 22:51:49,337:INFO:_master_model_container: 8
2023-11-15 22:51:49,337:INFO:_display_container: 2
2023-11-15 22:51:49,337:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-15 22:51:49,337:INFO:create_model() successfully completed......................................
2023-11-15 22:51:49,414:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:49,414:INFO:Creating metrics dataframe
2023-11-15 22:51:49,421:INFO:Initializing Ada Boost Classifier
2023-11-15 22:51:49,421:INFO:Total runtime is 0.0930326779683431 minutes
2023-11-15 22:51:49,423:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:49,423:INFO:Initializing create_model()
2023-11-15 22:51:49,423:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:49,423:INFO:Checking exceptions
2023-11-15 22:51:49,423:INFO:Importing libraries
2023-11-15 22:51:49,424:INFO:Copying training dataset
2023-11-15 22:51:49,426:INFO:Defining folds
2023-11-15 22:51:49,426:INFO:Declaring metric variables
2023-11-15 22:51:49,428:INFO:Importing untrained model
2023-11-15 22:51:49,430:INFO:Ada Boost Classifier Imported successfully
2023-11-15 22:51:49,434:INFO:Starting cross validation
2023-11-15 22:51:49,435:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:50,048:INFO:Calculating mean and std
2023-11-15 22:51:50,049:INFO:Creating metrics dataframe
2023-11-15 22:51:50,051:INFO:Uploading results into container
2023-11-15 22:51:50,051:INFO:Uploading model into container now
2023-11-15 22:51:50,052:INFO:_master_model_container: 9
2023-11-15 22:51:50,052:INFO:_display_container: 2
2023-11-15 22:51:50,052:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=29)
2023-11-15 22:51:50,052:INFO:create_model() successfully completed......................................
2023-11-15 22:51:50,130:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:50,130:INFO:Creating metrics dataframe
2023-11-15 22:51:50,138:INFO:Initializing Gradient Boosting Classifier
2023-11-15 22:51:50,138:INFO:Total runtime is 0.10498571395874023 minutes
2023-11-15 22:51:50,141:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:50,141:INFO:Initializing create_model()
2023-11-15 22:51:50,141:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:50,141:INFO:Checking exceptions
2023-11-15 22:51:50,141:INFO:Importing libraries
2023-11-15 22:51:50,141:INFO:Copying training dataset
2023-11-15 22:51:50,143:INFO:Defining folds
2023-11-15 22:51:50,143:INFO:Declaring metric variables
2023-11-15 22:51:50,146:INFO:Importing untrained model
2023-11-15 22:51:50,148:INFO:Gradient Boosting Classifier Imported successfully
2023-11-15 22:51:50,153:INFO:Starting cross validation
2023-11-15 22:51:50,154:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:57,342:INFO:Calculating mean and std
2023-11-15 22:51:57,343:INFO:Creating metrics dataframe
2023-11-15 22:51:57,347:INFO:Uploading results into container
2023-11-15 22:51:57,348:INFO:Uploading model into container now
2023-11-15 22:51:57,348:INFO:_master_model_container: 10
2023-11-15 22:51:57,348:INFO:_display_container: 2
2023-11-15 22:51:57,349:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=29, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-15 22:51:57,349:INFO:create_model() successfully completed......................................
2023-11-15 22:51:57,435:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:57,435:INFO:Creating metrics dataframe
2023-11-15 22:51:57,443:INFO:Initializing Linear Discriminant Analysis
2023-11-15 22:51:57,443:INFO:Total runtime is 0.22672851880391437 minutes
2023-11-15 22:51:57,445:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:57,445:INFO:Initializing create_model()
2023-11-15 22:51:57,445:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:57,445:INFO:Checking exceptions
2023-11-15 22:51:57,445:INFO:Importing libraries
2023-11-15 22:51:57,445:INFO:Copying training dataset
2023-11-15 22:51:57,448:INFO:Defining folds
2023-11-15 22:51:57,448:INFO:Declaring metric variables
2023-11-15 22:51:57,450:INFO:Importing untrained model
2023-11-15 22:51:57,452:INFO:Linear Discriminant Analysis Imported successfully
2023-11-15 22:51:57,458:INFO:Starting cross validation
2023-11-15 22:51:57,458:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:57,599:INFO:Calculating mean and std
2023-11-15 22:51:57,599:INFO:Creating metrics dataframe
2023-11-15 22:51:57,602:INFO:Uploading results into container
2023-11-15 22:51:57,602:INFO:Uploading model into container now
2023-11-15 22:51:57,602:INFO:_master_model_container: 11
2023-11-15 22:51:57,603:INFO:_display_container: 2
2023-11-15 22:51:57,603:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-15 22:51:57,603:INFO:create_model() successfully completed......................................
2023-11-15 22:51:57,679:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:57,679:INFO:Creating metrics dataframe
2023-11-15 22:51:57,687:INFO:Initializing Extra Trees Classifier
2023-11-15 22:51:57,687:INFO:Total runtime is 0.2308013319969177 minutes
2023-11-15 22:51:57,689:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:57,689:INFO:Initializing create_model()
2023-11-15 22:51:57,690:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:57,690:INFO:Checking exceptions
2023-11-15 22:51:57,690:INFO:Importing libraries
2023-11-15 22:51:57,690:INFO:Copying training dataset
2023-11-15 22:51:57,692:INFO:Defining folds
2023-11-15 22:51:57,692:INFO:Declaring metric variables
2023-11-15 22:51:57,694:INFO:Importing untrained model
2023-11-15 22:51:57,696:INFO:Extra Trees Classifier Imported successfully
2023-11-15 22:51:57,700:INFO:Starting cross validation
2023-11-15 22:51:57,701:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:51:58,228:INFO:Calculating mean and std
2023-11-15 22:51:58,229:INFO:Creating metrics dataframe
2023-11-15 22:51:58,231:INFO:Uploading results into container
2023-11-15 22:51:58,231:INFO:Uploading model into container now
2023-11-15 22:51:58,232:INFO:_master_model_container: 12
2023-11-15 22:51:58,232:INFO:_display_container: 2
2023-11-15 22:51:58,232:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=29, verbose=0, warm_start=False)
2023-11-15 22:51:58,232:INFO:create_model() successfully completed......................................
2023-11-15 22:51:58,310:INFO:SubProcess create_model() end ==================================
2023-11-15 22:51:58,310:INFO:Creating metrics dataframe
2023-11-15 22:51:58,318:INFO:Initializing Extreme Gradient Boosting
2023-11-15 22:51:58,318:INFO:Total runtime is 0.24131975173950193 minutes
2023-11-15 22:51:58,320:INFO:SubProcess create_model() called ==================================
2023-11-15 22:51:58,321:INFO:Initializing create_model()
2023-11-15 22:51:58,321:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:51:58,321:INFO:Checking exceptions
2023-11-15 22:51:58,321:INFO:Importing libraries
2023-11-15 22:51:58,321:INFO:Copying training dataset
2023-11-15 22:51:58,323:INFO:Defining folds
2023-11-15 22:51:58,323:INFO:Declaring metric variables
2023-11-15 22:51:58,325:INFO:Importing untrained model
2023-11-15 22:51:58,328:INFO:Extreme Gradient Boosting Imported successfully
2023-11-15 22:51:58,332:INFO:Starting cross validation
2023-11-15 22:51:58,333:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:52:00,452:INFO:Calculating mean and std
2023-11-15 22:52:00,453:INFO:Creating metrics dataframe
2023-11-15 22:52:00,456:INFO:Uploading results into container
2023-11-15 22:52:00,457:INFO:Uploading model into container now
2023-11-15 22:52:00,457:INFO:_master_model_container: 13
2023-11-15 22:52:00,457:INFO:_display_container: 2
2023-11-15 22:52:00,458:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)
2023-11-15 22:52:00,458:INFO:create_model() successfully completed......................................
2023-11-15 22:52:00,535:INFO:SubProcess create_model() end ==================================
2023-11-15 22:52:00,535:INFO:Creating metrics dataframe
2023-11-15 22:52:00,545:INFO:Initializing Light Gradient Boosting Machine
2023-11-15 22:52:00,545:INFO:Total runtime is 0.2784274578094482 minutes
2023-11-15 22:52:00,547:INFO:SubProcess create_model() called ==================================
2023-11-15 22:52:00,547:INFO:Initializing create_model()
2023-11-15 22:52:00,547:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:52:00,547:INFO:Checking exceptions
2023-11-15 22:52:00,547:INFO:Importing libraries
2023-11-15 22:52:00,547:INFO:Copying training dataset
2023-11-15 22:52:00,551:INFO:Defining folds
2023-11-15 22:52:00,551:INFO:Declaring metric variables
2023-11-15 22:52:00,554:INFO:Importing untrained model
2023-11-15 22:52:00,556:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-15 22:52:00,563:INFO:Starting cross validation
2023-11-15 22:52:00,564:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-15 22:52:15,123:INFO:Calculating mean and std
2023-11-15 22:52:15,124:INFO:Creating metrics dataframe
2023-11-15 22:52:15,126:INFO:Uploading results into container
2023-11-15 22:52:15,136:INFO:Uploading model into container now
2023-11-15 22:52:15,136:INFO:_master_model_container: 14
2023-11-15 22:52:15,136:INFO:_display_container: 2
2023-11-15 22:52:15,137:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=29, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-11-15 22:52:15,137:INFO:create_model() successfully completed......................................
2023-11-15 22:52:15,228:INFO:SubProcess create_model() end ==================================
2023-11-15 22:52:15,228:INFO:Creating metrics dataframe
2023-11-15 22:52:15,238:INFO:Initializing CatBoost Classifier
2023-11-15 22:52:15,238:INFO:Total runtime is 0.5233214577039083 minutes
2023-11-15 22:52:15,241:INFO:SubProcess create_model() called ==================================
2023-11-15 22:52:15,241:INFO:Initializing create_model()
2023-11-15 22:52:15,241:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fa92c58ca00>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fa92c58cc40>, model_only=True, return_train_score=False, kwargs={})
2023-11-15 22:52:15,241:INFO:Checking exceptions
2023-11-15 22:52:15,242:INFO:Importing libraries
2023-11-15 22:52:15,242:INFO:Copying training dataset
2023-11-15 22:52:15,245:INFO:Defining folds
2023-11-15 22:52:15,246:INFO:Declaring metric variables
2023-11-15 22:52:15,248:INFO:Importing untrained model
2023-11-15 22:52:15,251:INFO:CatBoost Classifier Imported successfully
2023-11-15 22:52:15,256:INFO:Starting cross validation
2023-11-15 22:52:15,257:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
